version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub

python:
  setup_py_install: true
  version: 3.6
  install:
    - requirements: requirements-doc.txt
    - method: pip
      path: .
